# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('year_heaven_letter', models.CharField(max_length=6)),
                ('year_ground_letter', models.CharField(max_length=6)),
                ('month_heaven_letter', models.CharField(max_length=6)),
                ('day_heaven_letter', models.CharField(max_length=6)),
            ],
        ),
    ]
