# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'manseCalendar', '0001_initial'), (b'manseCalendar', '0002_auto_20161224_1830'), (b'manseCalendar', '0003_auto_20170104_2128'), (b'manseCalendar', '0004_auto_20170104_2129')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('year_heaven_letter', models.CharField(max_length=6, null=True)),
                ('year_ground_letter', models.CharField(max_length=6, null=True)),
                ('month_heaven_letter', models.CharField(max_length=6, null=True)),
                ('day_heaven_letter', models.CharField(max_length=6, null=True)),
                ('day_ground_letter', models.CharField(max_length=6, null=True)),
                ('is_lunar_leap_month', models.BooleanField(default=False)),
                ('is_solar_term', models.BooleanField(default=False)),
                ('lunar_day', models.PositiveSmallIntegerField(null=True)),
                ('lunar_month', models.PositiveSmallIntegerField(null=True)),
                ('lunar_year', models.PositiveSmallIntegerField(null=True)),
                ('month_ground_letter', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
