# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0002_auto_20161224_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
