# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0003_auto_20170104_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarterm',
            name='month_ground_letter',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='solarterm',
            name='month_heaven_letter',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
