# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0003_auto_20170108_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='lunar_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='lunar_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='lunar_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
