# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0003_auto_20170108_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='solarterm',
            options={'ordering': ['time']},
        ),
    ]
