# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0004_auto_20170118_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
