# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manseCalendar', '0005_day_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_of_week',
            new_name='week_day',
        ),
    ]
